# Generated by Django 3.0.10 on 2020-11-25 08:55

from django.db import migrations, models
import django.utils.timezone
import kaffepause.common.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.DateTimeField(default=kaffepause.common.utils.thirty_minutes_from_now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BreakHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Break history',
                'verbose_name_plural': 'Break histories',
            },
        ),
        migrations.CreateModel(
            name='BreakInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.CharField(blank=True, max_length=75, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('reply', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('ignored', 'Ignored')], max_length=10, null=True)),
                ('expiry', models.DateTimeField(default=kaffepause.common.utils.three_hours_from_now)),
            ],
            options={
                'verbose_name': 'Break invitation',
                'verbose_name_plural': 'Break invitations',
                'ordering': ('-created', 'is_seen'),
            },
        ),
    ]
