# Generated by Django 3.0.10 on 2020-11-14 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinvitation',
            name='expiry',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 19, 31, 47, 48791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='breakinvitation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 17, 1, 47, 48265, tzinfo=utc)),
        ),
    ]
