# Generated by Django 3.0.10 on 2020-11-24 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breaks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinvitation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_invites', related_query_name='break_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakinvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakinvitation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='breaks.Break'),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_breaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='break',
            name='participants',
            field=models.ManyToManyField(related_name='breaks', related_query_name='break', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='breakinvitation',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'subject'), name='unique-invitation'),
        ),
    ]
