# Generated by Django 3.0.10 on 2020-11-14 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_auto_20201114_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinvitation',
            name='expiry',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 19, 46, 55, 252990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='breakinvitation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 17, 16, 55, 252841, tzinfo=utc)),
        ),
    ]
