# Generated by Django 3.0.10 on 2020-11-15 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0004_auto_20201114_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakinvitation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='break',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 9, 34, 34, 387079, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='breakinvitation',
            name='message',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='breakinvitation',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='breaks.Break'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakinvitation',
            name='expiry',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 12, 4, 34, 388819, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='breakinvitation',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'subject'), name='unique-invitation'),
        ),
    ]
