# Generated by Django 3.0.10 on 2020-11-15 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0005_auto_20201115_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 10, 39, 58, 338763)),
        ),
        migrations.AlterField(
            model_name='breakinvitation',
            name='expiry',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 12, 9, 58, 340939, tzinfo=utc)),
        ),
    ]
