# Generated by Django 3.0.10 on 2020-11-15 09:16

from django.db import migrations, models
import kaffepause.breaks.models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0007_auto_20201115_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.TimeField(default=kaffepause.breaks.models.thirty_minutes_from_now),
        ),
        migrations.AlterField(
            model_name='breakinvitation',
            name='expiry',
            field=models.TimeField(default=kaffepause.breaks.models.three_hours_from_now),
        ),
    ]
