# Generated by Django 3.0.10 on 2020-11-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0008_auto_20201115_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakhistory',
            old_name='related_break',
            new_name='subject',
        ),
    ]
