version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: kaffepause_local_django
    container_name: django
    depends_on:
      - postgres
      - neo4j
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.neo4j
    ports:
      - "8000:8000"
    command: /start

  neo4j:
    image: neo4j:3.5
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    env_file:
      - ./.envs/.local/.neo4j

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kaffepause_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    container_name: phppgadmin
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .envs/.local/.phppgadmin

  docs:
    image: kaffepause_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kaffepause:/app/kaffepause:z
    ports:
      - "7000:7000"
