version: '3'

volumes:
  production_traefik: {}

services:
  api:
    container_name: api
    image: kaffepause.azurecr.io/kaffepause:latest
    command: /start
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:6

  traefik:
    image: kaffepause.azurecr.io/kaffepause_production_traefik:latest
    depends_on:
      - api
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "8080:8080" # Traefik dashboard
      - "80:80"
      - "443:443"
