version: '3'

volumes:
  production_traefik: {}

services:
  django:
    container_name: django
    image: kaffepause.azurecr.io/kaffepause:latest
    command: /start
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`kaffepause-api.azurewebsites.net`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  redis:
    container_name: redis
    image: redis:6

  traefik:
    image: kaffepause.azurecr.io/kaffepause_production_traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
#      - "8080:8080" # Traefik dashboard
      - "80:80"
      - "443:443"
