version: '3'

volumes:
  production_traefik: {}
  azure_file_storage: {}

services:
  django:
    container_name: django
    image: kaffepause.azurecr.io/kaffepause:latest
    command: /start
#    ports:
#      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:6
    env_file:
          - .env

  neo4j:
    image: neo4j:4.1
    container_name: neo4j
    restart: always
#    ports:
 #     - 7474:7474
  #    - 7687:7687
    volumes:
      - azure_file_storage:/neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS='["apoc"]'
#      - NEO4J_dbms_memory_heap_max_size=1G
#      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
    env_file:
          - .env

  traefik:
    image: kaffepause.azurecr.io/kaffepause_production_traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '80:80'
      - '443:443'
    env_file:
          - .env
