# Generated by Django 3.0.10 on 2020-11-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'Check-in', 'verbose_name_plural': 'Check-ins'},
        ),
    ]
