# Generated by Django 3.0.10 on 2020-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_auto_20201114_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='intensity',
            field=models.CharField(blank=True, choices=[('intensly', 'Intensely'), ('focused', 'Focused'), ('not so focused', 'Not So Focused'), ('unfocused', 'Unfocused')], default='focused', max_length=14),
        ),
    ]
