# Generated by Django 3.0.10 on 2020-11-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('verb', models.CharField(max_length=100, verbose_name='verb')),
                ('slug', models.CharField(help_text="When a mutual relationship exists, i.e. 'friends', 'requested'", max_length=100, verbose_name='slug')),
                ('login_required', models.BooleanField(default=False, help_text='Users must be logged in to see these relationships', verbose_name='login required')),
                ('private', models.BooleanField(default=False, help_text='Only the user who owns these relationships can see them', verbose_name='private')),
            ],
            options={
                'verbose_name': 'Relationship status',
                'verbose_name_plural': 'Relationship statuses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('weight', models.FloatField(blank=True, default=1.0, null=True, verbose_name='weight')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to=settings.AUTH_USER_MODEL, verbose_name='from users')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relationships.RelationshipStatus', verbose_name='status')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendship',
                'ordering': ('created',),
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
