# Generated by Django 3.0.10 on 2020-11-07 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ('since',), 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendship'},
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='created',
        ),
        migrations.AddField(
            model_name='relationship',
            name='since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='since'),
            preserve_default=False,
        ),
    ]
