# Generated by Django 3.0.10 on 2020-11-26 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('verb', models.CharField(max_length=100, verbose_name='verb')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('from_slug', models.CharField(help_text="Denote the friendship from the user, i.e. user is 'requesting'", max_length=100, verbose_name='from slug')),
                ('to_slug', models.CharField(help_text="Denote the friendship to the user, i.e. user is 'requested' by", max_length=100, verbose_name='to slug')),
                ('login_required', models.BooleanField(default=False, help_text='Users must be logged in to see these friendship', verbose_name='login required')),
                ('private', models.BooleanField(default=False, help_text='Only the user who owns these friendship can see them', verbose_name='private')),
            ],
            options={
                'verbose_name': 'Friendship status',
                'verbose_name_plural': 'Friendship statuses',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('weight', models.FloatField(blank=True, default=1.0, null=True, verbose_name='weight')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to=settings.AUTH_USER_MODEL, verbose_name='from users')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='friendships.FriendshipStatus', verbose_name='status')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'ordering': ('modified',),
            },
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique-participants'),
        ),
    ]
