# Generated by Django 3.0.10 on 2020-11-04 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Are friends'), (2, 'Is requested'), (3, 'Is blocked')], default=2)),
                ('score', models.PositiveIntegerField(default=0)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_addressed_at_user', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requested_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['score'],
                'unique_together': {('requester', 'addressee')},
                'index_together': {('requester', 'addressee')},
            },
        ),
    ]
