# Generated by Django 3.0.10 on 2020-11-08 20:28

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('modified',), 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendship'},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='since',
        ),
        migrations.AddField(
            model_name='friendship',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
