# Generated by Django 3.0.10 on 2020-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_auto_20201108_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('modified',), 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique-friendship',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique-participants'),
        ),
    ]
