#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

python /app/manage.py migrate --noinput


# Maybe these should be in prod start
#python /app/manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); exit(User.objects.exists())" && python /app/manage.py createsuperuser --noinput

#python /app/manage.py load_locations

#python -c <<EOF |
#from django.db import IntegrityError
#try:
#  python manage.py install_labels
#except IntegrityError:
#  print("Already installed")
#EOF

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --timeout 600 --chdir=/app
