#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

python /app/manage.py migrate --noinput

python /app/manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); exit(User.objects.exists())" && python /app/manage.py createsuperuser --noinput

#python /app/manage.py install_labels
#python /app/manage.py load_locations --noinput


/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --timeout 600 --chdir=/app
