log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'

http:
  routers:
    web-secure-router:
      rule: 'Host(`kaffepause.azurewebsites.net`)'
      entryPoints:
#        - web-secure
        - web
      middlewares:
        - csrf
      service: django

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken', 'x-xsrf-token']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
