# Generated by Django 3.0.10 on 2020-11-08 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', through='friendships.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
