# Generated by Django 3.0.10 on 2020-11-29 18:26

from django.db import migrations
import kaffepause.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', kaffepause.accounts.models.AccountManager()),
            ],
        ),
    ]
